# Generated by Django 5.1.1 on 2024-09-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0022_alter_validationkey_private_key"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="validationkey",
            name="private_key_unique",
        ),
        migrations.RemoveConstraint(
            model_name="validationkey",
            name="pv_key_acct_doc_num_unique",
        ),
        migrations.AddField(
            model_name="validationkey",
            name="private_key_hash",
            field=models.CharField(
                default="blank",
                editable=False,
                help_text="The SHA512 has of the private key. This is used to enforce uniqueness in the database.",
                max_length=128,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="validationkey",
            constraint=models.UniqueConstraint(
                fields=("private_key_hash",),
                name="private_key_hash_unique",
                violation_error_message="The private key hash already exixts.",
            ),
        ),
        migrations.AddConstraint(
            model_name="validationkey",
            constraint=models.UniqueConstraint(
                fields=("private_key_hash", "account_id", "document_number"),
                name="private_key_hash_acct_doc_num_unique",
                violation_error_message="This key hash is already tied to this account and document number.",
            ),
        ),
    ]
